jobs:
  - script: |
      folder('ci') {
        displayName("CD")
      }

      pipelineJob('ci/packer') {
        displayName("Packer CD")
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/vucong2409/sc-lab-3-packer')
                  credentials('git-cred')
                }
                branch('*/main')
              }
            }
            lightweight()
          }
        }
      }
