jobs:
  - script: |
      folder('cd') {
        displayName("CD")
      }

      pipelineJob('cd/packer') {
        displayName("Packer CD")
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/vucong2409/sc-lab-3-packer')
                  credentials('git-cred')
                }
                branch('*/main')
              }
            }
            lightweight()
          }
        }
      }

      multibranchPipelineJob('cd/terraform') {
        displayName("Terraform")
        branchSources {
          git {
            id('terraformrepo')
            remote('https://github.com/vucong2409/sc-lab-3-iac')
            credentialsId('git-cred')
            includes('*')
          }
        }
        configure {
          def traits = it / sources / data / 'jenkins.branch.BranchSource' / source / traits
          traits << 'jenkins.plugins.git.traits.TagDiscoveryTrait' {}
          traits << 'jenkins.plugins.git.traits.BranchDiscoveryTrait' {}
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep(20)
          }
        }
      }

      multibranchPipelineJob('cd/cat-be') {
        displayName("Cat-BE CD")
        branchSources {
          git {
            id('terraformrepo')
            remote('https://github.com/vucong2409/cat-be')
            credentialsId('git-cred')
            includes('*')
          }
        }
        configure {
          def traits = it / sources / data / 'jenkins.branch.BranchSource' / source / traits
          traits << 'jenkins.plugins.git.traits.TagDiscoveryTrait' {}
          traits << 'jenkins.plugins.git.traits.BranchDiscoveryTrait' {}
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep(20)
          }
        }
      }

      multibranchPipelineJob('cd/cat-fe') {
        displayName("Cat-FE CD")
        branchSources {
          git {
            id('terraformrepo')
            remote('https://github.com/vucong2409/cat-ui-fe')
            credentialsId('git-cred')
            includes('*')
          }
        }
        configure {
          def traits = it / sources / data / 'jenkins.branch.BranchSource' / source / traits
          traits << 'jenkins.plugins.git.traits.TagDiscoveryTrait' {}
          traits << 'jenkins.plugins.git.traits.BranchDiscoveryTrait' {}
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep(20)
          }
        }
      }

      pipelineJob('cd/cat-release') {
        displayName("Release CAT")
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/vucong2409/sc-lab-3-app-stack')
                  credentials('git-cred')
                }
                branch('*/main')
              }
            }
            lightweight()
          }
        }
      }
